/**
 * Created by hxsd on 2016/12/22.
 */
var myapp=angular.module("myapp",["ionic"]);

    myapp.config(function($stateProvider,$urlRouterProvider){
        $stateProvider
            //一级路由
            .state("tabs",{
                url:"/tabs",
                abstract:true,
                templateUrl:"templates/tabs/tabs.html"
            })
            //二级路由
            .state("tabs.home",{
                url:"/home",
                views:{"tab-home":{
                    templateUrl:"templates/home/home.html"
                }}
            })
            .state("tabs.muji",{
                url:"/muji",
                views:{"tab-home":{
                    templateUrl:"templates/muji/muji.html"
                }}
            })
            .state("cart",{
                url:"/cart",
                templateUrl:"templates/cart/cart.html",
                controller:"cartCtrl"
            })
            .state("tabs.category",{
                url:"/category",
                views:{"tab-category":{
                    templateUrl:"templates/category/category.html",
                    controller:"categoryCtrl"
                }}
            })
            .state("tabs.detail",{
                url:"/detail?:text",
                views:{"tab-category": {
                    templateUrl:"templates/detail/detail.html",
                    controller:"deatailCtrl"
                }}
            })
            .state("tabs.master",{
                url:"/master",
                views:{"tab-master":{
                    templateUrl:"templates/master/master.html",
                    controller:"masterCtrl"
                }}
            })
            .state("tabs.information",{
                url:"/information?:name",
                views:{"tab-master":{
                    templateUrl:"templates/information/information.html",
                    controller:"informationCtrl"
                }}
            })
            .state("tabs.share",{
                url:"/share",
                views:{"tab-share":{
                    templateUrl:"templates/share/share.html",
                    controller:"shareCtrl"
                }}
            })
            .state("tabs.share_detail",{
                url:"/share_detail?:name",
                views:{"tab-share":{
                    templateUrl:"templates/share_detail/share_detail.html",
                    controller:"share_detailCtrl"
                }}
            })
            .state("tabs.personal",{
                url:"/personal",
                views:{"tab-personal":{
                    templateUrl:"templates/personal/personal.html"
                }}
            })
            .state("slide",{
                url:"/slide",
                templateUrl:"templates/slide/slide.html"
            });
        //默认URL首页
        $urlRouterProvider.otherwise("/slide")
    });